@startuml "Modelo conceitual"

abstract class People {
    id: Long
    name : String
    phone: String
    email: String
    comments: String
}

class Professional {
    active: boolean    
}

class Client {
    gender: MALE | FEMALE
    dayOfBirth: LocalDate
}


'private or health insurance
class AppoitmentType {
    id: Integer
    type: String
}

class Comment {
    id: Long
    comment: String
}
class WorkSchedule {
    id: Integer
    dayWeek: DayOfWeek
    startTime: Time
    endTime: Time
}

class Area {
    id: Integer
    name: String
}

class Appointment {
    id: Long
    date: LocalTime
    startTime: Time
    status: PRESENT | ABSENT | OPEN
}


class User {
    password: String
    type: ADMIN | OPERATOR

}

People              <|--            Client
People              <|--            Professional
People              <|--            User
Professional        o--     "0..*"  Area
Professional        *--     "0..*"  WorkSchedule
Appointment         o--     "0..1"  AppoitmentType
Appointment "0..*"  -l-     "0..1"  Client            : has ->
Appointment "0..*"  -r-     "0..1"  Professional      : <- has  
Appointment         *--     "0..*"  Comment           




@enduml