@startuml "Modelo conceitual"

abstract class People {
    id: Long
    name : String
    phone: String
    email: String
    comments: String
}

class Professional {
    active: boolean    
}

class Client {
    gender: M | F
    dayOfBirth: LocalDate
}


'private or health insurance
class AppoitmentType {
    id: Integer
    type: String
}

class WorkSchedule {
    id: Integer
    dayWeek: DayOfWeek
    startTime: Time
    endTime: Time
}

class Area {
    id: Integer
    name: String
}

class Appointment {
    id: Long
    date: LocalTime
    startTime: Time
    comments: String
}

class BlockedDate {
    id: Integer
    date: LocalDate
    startTime: Time
    endTime: Time
}

class User {
    password: String
    type: ADMIN | OPERATOR

}

People              <|--            Client
People              <|--            Professional
People              <|--            User
Professional        o--     "0..*"  Area
Professional        *--     "0..*"  WorkSchedule
Professional        *--     "0..*"  BlockedDate
Appointment         o--     "0..1"  AppoitmentType
Appointment "0..*"  -l-     "0..1"  Client            : has ->
Appointment "0..*"  -r-     "0..1"  Professional      : <- has  




@enduml