@startuml "Use Cases"
left to right direction
actor Operator as o
actor Admin as a
package Schedule{
  usecase "Create Appointment" as UC1
  usecase "Cancel Appointment" as UC2
  usecase "Confirm Appointment" as UC3
  usecase "Define Work WeekDays" as UC4
  usecase "Search Professional Availability Days" as UC5
  usecase "Search Professional Availability Times" as UC6
  usecase "Search Client History" as UC7
}
o <|-right- a
o --> UC1
o --> UC2
o --> UC3
o --> UC7
a --> UC4
(UC5) .up.> (UC1) : <<includes>>
(UC6) .up.> (UC1) : <<includes>>
@enduml